# Generated by Django 6.1.1 on 2026-10-04 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_activity_calories_activity_protein_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='protein',
        ),
        migrations.AddField(
            model_name='goal',
            name='calories',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='goal',
            name='protein',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
