# Generated by Django 6.1.1 on 2026-10-04 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_badge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('metric', models.CharField(choices=[('steps', 'Steps'), ('protein', 'Protein (g)'), ('logging', 'Days logged')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('invite_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
