# Generated by Django 6.1.1 on 2026-10-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_challenge_weekly_email_reportpref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='weekly_email',
        ),
        migrations.AddField(
            model_name='reportpref',
            name='weekly_email',
            field=models.BooleanField(default=False),
        ),
    ]
